steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/food-track-web-app', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/food-track-web-app']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'food-track-web-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/food-track-web-app'
      - '--region'
      - 'australia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID,FLASK_ENV=production,OAUTHLIB_INSECURE_TRANSPORT=0'
      - '--update-secrets'
      - 'web-app=web-app:latest'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--service-account'
      - '$PROJECT_ID@appspot.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/food-track-web-app'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'